#!/bin/sh

set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
version_file="$repo_root/Sources/SwiftLens/Version.generated.swift"
version=${1:-v0.1.0}

cat >"$version_file" <<EOF
// Generated by scripts/generate-version-file.sh. Do not edit manually.

enum SwiftLensVersion {
    static let current = "$version"
}
EOF
