#!/bin/sh

set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
version_file="$repo_root/Sources/SwiftLens/Version.generated.swift"

[ "$#" -eq 1 ] || {
    printf '%s\n' 'Usage: scripts/write-release-version-source.sh <version>' >&2
    exit 1
}

version=$1

cat >"$version_file" <<EOF
// Generated by scripts/write-release-version-source.sh. Do not edit manually.

enum SwiftLensVersion {
    static let current = "$version"
}
EOF
